stages:
  - linter
  - fetch
  - build

cache: &global_cache
  key: fetch-build
  paths:
    - yocto/build_arm/
    - yocto/build_amd64/
    - yocto/meta-openembedded/
    - yocto/poky/
    - yocto/meta-virtualization/

linter:
  stage: linter
  script:
    - source scripts/linter.sh commit-msg
    #source scripts/linter.sh branch-name
    - source scripts/linter.sh json

fetch:
  stage: fetch
  script:
    - cd yocto
    - bash build.sh fetch thud
    - cd ..
  cache:
    # inherit all global cache settings
    <<: *global_cache

build:
  stage: build
  script:
    - cd yocto
    - bash build.sh -a arm build master
    - cd .
  cache:
    # inherit all global cache settings
    <<: *global_cache
