stages:
  - linter
  - fetch
  - build

cache: &global_cache
  key: fetch-build
  paths:
    - yocto/build_arm/
    - yocto/build_amd64/
    - yocto/meta-openembedded/
    - yocto/poky/
    - yocto/meta-virtualization/

linter:
  stage: linter
  script:
    - source scripts/linter.sh commit-msg
    #source scripts/linter.sh branch-name
    - source scripts/linter.sh json

fetch-qemuarm:
  stage: fetch
  script:
    - cd yocto
    - bash build.sh -a arm -m qemuarm meta-fetch thud
    - bash build.sh -a arm -m qemuarm bitbake-fetch master
    - cd ..

fetch-qemux86:
  stage: fetch
  script:
    - cd yocto
    - bash build.sh -a amd64 -m qemux86 meta-fetch thud
    - bash build.sh -a amd64 -m qemux86 bitbake-fetch master 
    - cd ..

build-qemuarm:
  stage: build
  script:
    - cd yocto
    - bash build.sh -a arm -m qemuarm build master
    - cd .

build-qemux86:
  stage: build
  script:
    - cd yocto
    - bash build.sh -a amd64 -m qemux86 build master
    - cd .
