stages:
  - linter
  - fetch
  - build
  - run-test

# yocto arch/machine configs
.arm-config:
  variables:
    TARGET_ARCH: "arm"
    MACHINE_NAME: "qemuarm"

.amd64-config:
  variables:
    TARGET_ARCH: "amd64"
    MACHINE_NAME: "qemux86"

# artifact policy
.feature-deploy-artifact-policy:
  except:
    refs:
      - master
      - dev
  artifacts:
    paths:
      - deploy.tar.gz
    when: on_success
    expire_in: 15 mins

.dev-deploy-artifact-policy:
    only:
        refs:
          dev
    artifacts:
    paths:
      - deploy.tar.gz
    when: on_success
    expire_in: 1 week
  
.master-deploy-artifact-policy:
  only:
    refs:
      master
  artifacts:
    paths:
      - deploy.tar.gz
    when: on_success
    expire_in: 10 year

.feature-log-artifact-policy:
  except:
    refs:
      - master
      - dev
  artifacts:
    paths:
      - deploy.tar.gz
    when: on_success
    expire_in: 60 mins

.dev-deploy-artifact-policy:
  only:
    refs:
      - dev
  artifacts:
    paths:
      - deploy.tar.gz
    when: on_success
    expire_in: 10 year
  
.master-deploy-artifact-policy:
  only:
    refs:
      - master
  artifacts:
    paths:
      - deploy.tar.gz
    when: on_success
    expire_in: 10 year

linter:
  stage: linter
  script:
    - bash scripts/linter.sh commit-msg
    - bash scripts/linter.sh json
  interruptible: true

fetch-qemuarm:
  extends: .arm-config
  stage: fetch
  script:
    - bash yocto/build.sh meta-fetch thud
    - bash yocto/build.sh bitbake-fetch master
  interruptible: false
  only:
    changes:
      - yocto/*.*
      - .gitlab-ci.yml

fetch-qemux86:
  extends: .amd64-config
  stage: fetch
  script:
    - bash yocto/build.sh meta-fetch thud
    - bash yocto/build.sh bitbake-fetch master 
  interruptible: false
  only:
    changes:
      - yocto/*.*
      - .gitlab-ci.yml

## build arm/x86 feature/dev/master
.build-qemuarm:
  extends: .arm-config
  stage: build
  script:
    - bash yocto/build.sh build master
    - bash yocto/build.sh take-release
  interruptible: false
  dependencies:
    - fetch-qemuarm
  only:
    changes:
      - yocto/*.*
      - .gitlab-ci.yml

.build-qemux86:
  extends: .amd64-config
  stage: build
  script:
    - bash yocto/build.sh build master
    - bash yocto/build.sh take-release
  interruptible: false
  dependencies:
    - fetch-qemux86
  only:
    changes:
      - yocto/*.*
      - .gitlab-ci.yml

build-qemuarm-feature:
  extends: 
    - .feature-deploy-artifact-policy
    - .build-qemuarm

build-qemuarm-dev:
  extends: 
    - .dev-deploy-artifact-policy
    - .build-qemuarm

build-qemuarm-master:
  extends: 
    - .master-deploy-artifact-policy
    - .build-qemuarm

build-qemux86-feature:
  extends: 
    - .feature-deploy-artifact-policy
    - .build-qemux86

build-qemux86-dev:
  extends: 
    - .dev-deploy-artifact-policy
    - .build-qemux86

build-qemux86-master:
  extends: 
    - .master-deploy-artifact-policy
    - .build-qemux86

# run arm/x86 feature/dev/master
run-qemuarm:
  extends: .arm-config
  stage: run-test
  script:
  - bash yocto/build.sh runqemu
  - bash yocto/test.sh runqemu
  interruptible: true
  timeout: 5m
  only:
    changes:
      - yocto/*.*
      - .gitlab-ci.yml
      - scripts/tests/*.*

run-qemux86:
  extends: .amd64-config
  stage: run-test
  script:
  - bash yocto/build.sh runqemu
  - bash yocto/test.sh runqemu
  interruptible: true
  timeout: 5m
  only:
    changes:
      - yocto/*.*
      - .gitlab-ci.yml
      - scripts/tests/*.*